package com.win.ticket.domain;

public enum Diagnosis {
    CTO_SIN_POTENCIA,
    CTO_DEGRADADA,
    CTO_CON_PUERTOS_SIN_POTENCIA,
    CTO_con_puertos_degradados,
    CTO_con_intermitencia,
    LOS,
    CAJA_NAP_SIN_POTENCIA,
    CAJA_NAP_DEGRADADA,
    CAJA_NAP_CON_PUERTOS_SIN_POTENCIA,
    CAJA_NAP_CON_PUERTOS_DEGRADADOS,
    CTO_DESPRENDIDA,
    CAJA_NAP_DESPRENDIDA,
    CTO_SIN_FACTIBILIDAD_PARA_HACER_TRABAJO
}
