package com.win.ticket.domain;

public enum Diagnosis {
    CTO_SIN_POTENCIA,
    CTO_DEGRADADA,
    CTO_PUERTOS_SIN_POTENCIA,
    CTO_PUERTOS_DEGRADADOS,
    CTO_INTERMITENCIA,
    LOS,
    NAP_SIN_POTENCIA,
    NAP_DEGRADADA,
    NAP_PUERTOS_SIN_POTENCIA,
    NAP_PUERTOS_DEGRADADOS,
    CTO_DESPRENDIDA,
    NAP_DESPRENDIDA,
    CTO_SIN_FACTIBILIDAD
}
